{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mahongyin.AndroidMonitor",
    "module": "monitor-plugin",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "monitor-plugin-0.1.0.jar",
          "url": "monitor-plugin-0.1.0.jar",
          "size": 7589,
          "sha512": "2e5101d7d8663114e9577839083726aca0d3c45ed0e86e5bf1aefee6ee314e5b35d25e9b09dea539b6338c6adc9564d56374acf4d05e5282e6ac0f09f91e1d91",
          "sha256": "b6dd9c5006c9ba00af81745c7750334c4e89c1e77f1ad68cb5e7b1ee4c94d856",
          "sha1": "fa9abe636d16bb90524ae8b3b671791cb3ad0209",
          "md5": "d76604e4515208cd19cf1bc335293db2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "cn.quinnchen.hunter",
          "module": "hunter-transform",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "monitor-plugin-0.1.0.jar",
          "url": "monitor-plugin-0.1.0.jar",
          "size": 7589,
          "sha512": "2e5101d7d8663114e9577839083726aca0d3c45ed0e86e5bf1aefee6ee314e5b35d25e9b09dea539b6338c6adc9564d56374acf4d05e5282e6ac0f09f91e1d91",
          "sha256": "b6dd9c5006c9ba00af81745c7750334c4e89c1e77f1ad68cb5e7b1ee4c94d856",
          "sha1": "fa9abe636d16bb90524ae8b3b671791cb3ad0209",
          "md5": "d76604e4515208cd19cf1bc335293db2"
        }
      ]
    }
  ]
}
